//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace minipj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        [Display(Name = "User ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Tên người dùng không được rỗng")]
        [Display(Name = "Tên người dùng")]
        public string UserName { get; set; }

        [Display(Name = "Vị trí")]
        public string RoleUser { get; set; }


        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Password không được rỗng")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser")]
        [Display(Name = "Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email không được rỗng")]
        public string UserAccount { get; set; }
    }
}
